services:
  balance-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=balancedb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5438:5432'
