server:
  port: 9090

logging:
  level:
    org.springframework.security: debug

spring:
  application:
    name: auth-server
  security:
#    user:
#      name: user
#      password: password
    oauth2:
      authorizationserver:
        issuer: ${AUTH_SERVER_ISSUER:http://localhost:9090}
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: ${OIDC_CLIENT_SECRET_ENCODED:{noop}iaka}
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
                - "http://localhost:8080/login/oauth2/code/oidc-client"
                - "http://gateway:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
                - "http://gateway:8080/"
              scopes:
                - "openid"
                - "profile"
                - "email"
                - "user.read"
                - "user.write"
            require-authorization-consent: true