server:
    port: 8061
spring:
  application:
    name: shop

  r2dbc:
    url: ${SHOP_R2DBC_URL:r2dbc:postgresql://localhost:5433/shopdb}
    username: ${SHOP_R2DBC_USERNAME:myuser}
    password: ${SHOP_R2DBC_PASSWORD:secret}

  liquibase:
    url: ${SHOP_JDBC_URL:jdbc:postgresql://localhost:5433/shopdb}
    user: ${SHOP_JDBC_USERNAME:myuser}
    password: ${SHOP_JDBC_PASSWORD:secret}
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:${AUTH_ISSUER_URI:http://localhost:9090}}
  codec:
    max-in-memory-size: 10MB

springdoc:
  paths-to-match: /api/shop/**,/api/greetings/**