server:
  port: 8060
spring:
  application:
    name: greetings
  codec:
    max-in-memory-size: 10MB

jwt:
  jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:9090/auth/oauth2/jwks}
  trusted-issuers: ${TRUSTED_JWT_ISSUERS:http://localhost:8080/auth}

